spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: 'guest'
    password: 'guest'
  cloud:
    stream:
      bindings:
        input:
          destination: 'ezypay'
          group: 'poc'
          consumer:
            max-attempts: 1
      rabbit:
        bindings:
          input:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 7000
              dlq-dead-letter-exchange: